apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
data:
  db_host: jdbc:postgresql://{{ .Values.db.name }}:5432/moshaveran
  db_name: moshaveran

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    server {
      listen 80;
    
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }
    
      error_page   500 502 503 504  /50x.html;
    
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
    
    