apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: OWMyMzk0ZmZiMDdlODUwZjVlOTM4NzVkNmE3MDQ4N2MyMGI3MWE0Y2QzODhkNTg0
kind: Secret
metadata:
  name: dbsecret
  namespace: default
type: Opaque

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJvbWlkZGFnYWxhIiwicGFzc3dvcmQiOiIyNjEzNTAxMkAiLCJlbWFpbCI6Im9taWRkYWdhbGFAeWFob28uY29tIiwiYXV0aCI6ImIyMXBaR1JoWjJGc1lUb3lOakV6TlRBeE1rQT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
